version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=buynsell
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 5432:5432
    restart: always
  buynsell: 
    image: buynsell
    ports: 
      - 8080:8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 10; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@localhost:5432/buynsell
      # - PORT=3000  
    restart: always
  